# config/packages/fos_user.yaml
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "snryzhkov@gmail.com"
    sender_name: "admin"
  registration:
    confirmation:
      enabled: true
    form:
      type: App\LoginRegisterBundle\Form\RegistrationType
      name: app_user_registration
  profile:
    form:
      type: App\Form\ProfileFormType

